import http from 'node:http';
import {requestGuard} from './request-guard.mjs';
import {agentMap} from './agent-map.mjs';
import {readFile,writeFile,mkdir,rename} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes,timingSafeEqual} from 'node:crypto';
import {routes as seeds} from './public/seed.js';
const root=path.dirname(fileURLToPath(import.meta.url));
const guard=requestGuard();
const seedPlans=JSON.parse(await readFile(path.join(root,'public/seed-plans.json'),'utf8').catch(()=> '{}'));
const dataDir=process.env.DATA_DIR || path.join(root,'.data');
await mkdir(dataDir,{recursive:true});
const maps=agentMap({token:process.env.BAIDU_MAP_AUTH_TOKEN,dataDir});
let store={routes:{},replies:{}};
try{store=JSON.parse(await readFile(path.join(dataDir,'store.json'),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}
let writes=Promise.resolve();
function save(){const snapshot=JSON.stringify(store); writes=writes.then(async()=>{await writeFile(path.join(dataDir,'store.tmp'),snapshot,{mode:0o600});await rename(path.join(dataDir,'store.tmp'),path.join(dataDir,'store.json'));});return writes;}
const id=()=>randomBytes(12).toString('hex');
const txt=(v,max=150)=>typeof v==='string'?v.trim().slice(0,max):'';
const fail=(status,message)=>Object.assign(new Error(message),{status});
function media(v,kind){if(!v)return '';if(typeof v!=='string'||v.length>6_000_000)throw fail(400,'单个附件不能超过 4 MB');const re=kind==='photo'?/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/:/^data:audio\/(webm|mp4|ogg|mpeg|wav)(?:;codecs=[a-zA-Z0-9.,-]+)?;base64,[A-Za-z0-9+/=]+$/;if(!re.test(v))throw fail(400,'附件格式不支持');return v;}
function validate(body){if(!body||!Array.isArray(body.stops)||body.stops.length<2||body.stops.length>6)throw fail(400,'请添加 2 至 6 个地点');const r={title:txt(body.title,50),author:txt(body.author,30),city:txt(body.city,30),intro:txt(body.intro,350),dedication:txt(body.dedication,100),minutes:Math.min(240,Math.max(10,Number(body.minutes)||45)),theme:['lake','street'].includes(body.theme)?body.theme:'lake',demo:false,stops:body.stops.map(s=>{if(!s||typeof s!=='object')throw fail(400,'地点格式不正确');let point=null;if(s.point&&Number.isFinite(s.point.lng)&&Number.isFinite(s.point.lat)&&Math.abs(s.point.lng)<=180&&Math.abs(s.point.lat)<=90)point={lng:s.point.lng,lat:s.point.lat,coordType:s.point.coordType==='gcj02'?'gcj02':'bd09ll'};return {name:txt(s.name,80),address:txt(s.address,200),title:txt(s.title,80),story:txt(s.story,2000),prompt:txt(s.prompt,120),uid:txt(s.uid,80),point,art:['lake','street','bridge'].includes(s.art)?s.art:'lake',photo:media(s.photo,'photo'),audio:media(s.audio,'audio')};})};if(!r.title||!r.author||!r.city||!r.intro||r.stops.some(s=>!s.name||!s.story))throw fail(400,'请填写标题、署名、城市、开场白，以及每站的地点与故事');return r;}
async function body(req){let size=0,parts=[];for await(const part of req){size+=part.length;if(size>30_000_000)throw fail(413,'内容太大，请减少照片或缩短录音');parts.push(part);}try{const parsed=JSON.parse(Buffer.concat(parts).toString());if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw Error();return parsed;}catch{throw fail(400,'内容格式不正确');}}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.json':'application/json; charset=utf-8','.mp4':'video/mp4','.webm':'video/webm'};
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function auth(req,route){let token=req.headers.authorization?.replace(/^Bearer /,'')||'';const a=Buffer.from(token),b=Buffer.from(route.token);return a.length===b.length&&timingSafeEqual(a,b);}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');try{const url=new URL(req.url,'http://localhost');const pathname=url.pathname;if(req.method==='POST')guard(process.env.TRUST_CLOUDFLARE==='1'?req.headers['cf-connecting-ip']||req.socket.remoteAddress:req.socket.remoteAddress);if(req.method==='POST'&&req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host)throw fail(403,'来源不允许');
if(pathname==='/api/health'&&req.method==='GET')return send(res,200,{ok:true});
if(pathname==='/api/config'&&req.method==='GET')return send(res,200,{agentPlan:!!process.env.BAIDU_MAP_AUTH_TOKEN,seedPlans:true,preview:process.env.PREVIEW_MODE==='1',baiduAK:process.env.BAIDU_MAP_AK||'',localOnly:!process.env.PUBLIC_ORIGIN,publicOrigin:process.env.PUBLIC_ORIGIN||''});
if(pathname==='/api/map/search'&&req.method==='POST'){const b=await body(req),city=txt(b.city,30),query=txt(b.query,200);if(!city||!query)throw fail(400,'请填写城市和地点');return send(res,200,await maps.search(city,query));}
if(pathname==='/api/map/route'&&req.method==='POST'){const b=await body(req);if(!Array.isArray(b.stops)||b.stops.length<2||b.stops.length>6)throw fail(400,'请选择 2 至 6 个地点');const stops=b.stops.map(s=>{if(!s||typeof s!=='object')throw fail(400,'地点格式不正确');return {name:txt(s.name,80),uid:txt(s.uid,80),point:s.point};});if(stops.some(s=>!s.name||s.point&&(!Number.isFinite(s.point.lat)||!Number.isFinite(s.point.lng)||Math.abs(s.point.lat)>90||Math.abs(s.point.lng)>180)))throw fail(400,'地点坐标无效');const seed=seeds.find(r=>r.city===txt(b.city,30)&&r.stops.length===stops.length&&r.stops.every((s,i)=>s.uid===stops[i].uid&&s.name===stops[i].name&&s.point?.lng===stops[i].point?.lng&&s.point?.lat===stops[i].point?.lat));if(seed&&seedPlans[seed.id]?.legs.every(l=>l.ok))return send(res,200,{...seedPlans[seed.id],source:'verified-snapshot'});return send(res,200,await maps.route(txt(b.city,30),stops));}
if(pathname==='/api/routes'&&req.method==='GET')return send(res,200,seeds.map(({stops,...r})=>({...r,stopCount:stops.length})));
if(pathname==='/api/routes'&&req.method==='POST'){if(Object.keys(store.routes).length>=500)throw fail(429,'预览服务的路线容量已满。');const r=validate(await body(req));r.id=id();r.token=id();r.createdAt=new Date().toISOString();store.routes[r.id]=r;await save();return send(res,201,{id:r.id,token:r.token});}
const match=pathname.match(/^\/api\/routes\/([a-zA-Z0-9-]+)(?:\/(replies))?$/);if(match){const route=store.routes[match[1]]||seeds.find(r=>r.id===match[1]);if(!route)throw fail(404,'这封路线来信不存在');if(!match[2]&&req.method==='GET'){const {token,...publicRoute}=route;return send(res,200,publicRoute);}if(match[2]&&req.method==='POST'){const b=await body(req);const text=txt(b.message,1000),name=txt(b.name,30)||'路过的人';if(!text)throw fail(400,'先写一句想说的话吧');const list=store.replies[route.id] ||= [];if(list.length>=200)throw fail(429,'这条路线的演示回信已满');const reply={id:id(),name,message:text,photo:media(b.photo,'photo'),createdAt:new Date().toISOString()};list.push(reply);await save();return send(res,201,{id:reply.id,demo:!!route.demo});}if(match[2]&&req.method==='GET'){if(route.demo||!auth(req,route))throw fail(403,'只能从创建路线的浏览器查看回信');return send(res,200,store.replies[route.id]||[]);}}
if(pathname.startsWith('/api/'))throw fail(404,'接口不存在');if(req.method!=='GET'&&req.method!=='HEAD')throw fail(405,'请求方式不支持');const relative=pathname==='/'?'index.html':decodeURIComponent(pathname).replace(/^\//,'');const file=path.resolve(root,'public',relative);if(!file.startsWith(path.join(root,'public')+path.sep))throw fail(403,'路径不允许');const data=await readFile(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(req.method==='HEAD'?undefined:data);
}catch(e){send(res,e.status||(e.code==='ENOENT'?404:500),{error:e.status?e.message:e.code==='ENOENT'?'页面不存在':'保存失败，请稍后重试'});}});
server.listen(Number(process.env.PORT)||8793,process.env.HOST||'127.0.0.1',()=>console.log(`Borrow an afternoon: http://${process.env.HOST||'127.0.0.1'}:${server.address().port}`));
