import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
let proc,base,dir;
async function start(){proc=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:'18873',DATA_DIR:dir},stdio:['ignore','pipe','pipe']});await new Promise((res,rej)=>{proc.stdout.on('data',d=>{if(String(d).includes('Borrow an afternoon'))res();});proc.on('exit',c=>rej(new Error('Server exited '+c)));setTimeout(()=>rej(new Error('Server timeout')),5000).unref();});base='http://127.0.0.1:18873';}
async function request(url,body,token){return fetch(base+url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});}
before(async()=>{await mkdir(path.join(root,'.data'),{recursive:true});dir=await mkdtemp(path.join(root,'.data','test-'));await start();});
after(()=>proc?.kill());
test('Create route, shared read without token, private replies, survive restart',async()=>{const seed=await (await request('/api/routes/lake-letter')).json();const made=await request('/api/routes',{...seed,author:'验收测试',title:'测试路线'});assert.equal(made.status,201);const {id,token}=await made.json();const publicRoute=await (await request('/api/routes/'+id)).json();assert.equal(publicRoute.title,'测试路线');assert.equal(publicRoute.token,undefined);assert.equal(publicRoute.demo,false);const reply=await request(`/api/routes/${id}/replies`,{message:'我走过了第二站。',name:'测试读者'});assert.equal(reply.status,201);assert.equal((await request(`/api/routes/${id}/replies`)).status,403);assert.equal((await request(`/api/routes/${id}/replies`,null,'x'.repeat(token.length))).status,403);const got=await (await request(`/api/routes/${id}/replies`,null,token)).json();assert.equal(got[0].message,'我走过了第二站。');await new Promise(res=>{proc.on('exit',res);proc.kill();});await start();const persisted=await (await request(`/api/routes/${id}/replies`,null,token)).json();assert.equal(persisted.length,1);});
test('Validation rejects empty route, unsupported media, bad origins',async()=>{assert.equal((await request('/api/routes',{stops:[]})).status,400);const seed=await (await request('/api/routes/lake-letter')).json();seed.stops[0].photo='data:image/svg+xml;base64,PHN2Zz4=';assert.equal((await request('/api/routes',seed)).status,400);assert.equal((await request('/api/routes/lake-letter/replies',{message:'   '})).status,400);assert.equal((await fetch(base+'/api/routes',{method:'POST',headers:{Origin:'https://another.example','Content-Type':'application/json'},body:'{}'})).status,403);});
test('Seed gallery excludes private routes and demo inbox stays private',async()=>{const list=await (await request('/api/routes')).json();assert.equal(list.length,2);assert(list.every(x=>x.demo));assert.equal((await request('/api/routes/lake-letter/replies')).status,403);assert.equal((await request('/api/routes/missing')).status,404);assert.equal((await fetch(base+'/server.mjs')).status,404);assert.equal((await fetch(base+'/.data/store.json')).status,404);});
test('Home demo has confirmed GCJ02 places and complete dated Baidu plans',async()=>{for(const id of ['lake-letter','street-letter']){const route=await (await request('/api/routes/'+id)).json();assert(route.stops.every(s=>s.uid&&s.point?.coordType==='gcj02'));const res=await request('/api/map/route',{city:route.city,stops:route.stops});assert.equal(res.status,200);const plan=await res.json();assert.equal(plan.source,'verified-snapshot');assert.equal(plan.legs.length,2);assert(plan.legs.every(l=>l.ok&&l.distance>0&&l.duration>0));assert(Number.isFinite(Date.parse(plan.checkedAt)));}const config=await (await request('/api/config')).json();assert.equal(config.BAIDU_MAP_AUTH_TOKEN,undefined);assert.equal((await fetch(base+'/scripts/start-local.py')).status,404);});
test('Malformed payloads give useful validation errors',async()=>{for(const body of [null,[],{stops:[null,{}]}]){const response=await fetch(base+'/api/routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(response.status,400);}const bad=await request('/api/map/route',{stops:[null,null]});assert.equal(bad.status,400);});
